# joint_limits.yaml

default_velocity_scaling_factor: 0.05       # Default to 5% speed
default_acceleration_scaling_factor: 0.05   # Default to 5% acceleration

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 0.5                     # Slow down max speed (~28 deg/s)
    has_acceleration_limits: true         # Enable acceleration limiting
    max_acceleration: 0.5                 # Smooth ramping up/down
  joint2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  joint3:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  joint4:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5

  # Gripper Joints
  Tip_Gripper_Idol_Joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: true
    max_acceleration: 0.3
  Tip_Gripper_Servo_Joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: true
    max_acceleration: 0.3
  robot_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: true
    max_acceleration: 0.3
  robot_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: true
    max_acceleration: 0.3